"""
Projected Points Manager

Manages access to historical projected points data for fantasy football players.
Loads and provides week-by-week projection values from players_projected.csv
that were made at the start of each week for performance evaluation.

Key responsibilities:
- Loading projected points data from CSV files
- Name-based player lookup with case-insensitive matching
- Single-week projected points retrieval
- Multi-week projected points array generation
- Historical projected points access (weeks 1 to current-1)
- Handling missing or invalid projection data gracefully

Author: Kai Mizuno
"""

import pandas as pd
from pathlib import Path


class ProjectedPointsManager:
    """Manages access to projected points data for performance calculations."""

    def __init__(self, config, data_folder=None):
        """
        Initialize the ProjectedPointsManager.

        Args:
            config: ConfigManager instance for accessing CURRENT_NFL_WEEK
            data_folder: Path to data directory (optional, defaults to 'data')
        """
        # Store config reference to access current NFL week for historical data queries
        self.config = config

        # Store data folder path (use default 'data' if not provided)
        if data_folder is None:
            self.data_folder = Path('data')
        else:
            self.data_folder = Path(data_folder)

        # Will hold pandas DataFrame with projected points data
        # Initially None until data is loaded
        self.projected_data = None

        # Load projected points data immediately on initialization
        self._load_projected_data()

    def _load_projected_data(self):
        """Load the projected points CSV file and prepare for efficient lookups."""
        # Define path to projected points data file using data_folder
        # Expected format: CSV with columns [name, week_1_points, week_2_points, ..., week_17_points]
        projected_file = self.data_folder / 'players_projected.csv'

        # Validate file exists before attempting to load
        # This file must be generated by the player data fetcher first
        if not projected_file.exists():
            raise FileNotFoundError(
                f"Projected points file not found: {projected_file}. "
                "Run player data fetcher to generate this file."
            )

        # Check if file is empty before trying to parse
        # Empty files cause pandas to raise "No columns to parse from file" error
        if projected_file.stat().st_size == 0:
            raise ValueError(
                f"Projected points file is empty: {projected_file}. "
                "Run player data fetcher to regenerate this file."
            )

        # Load CSV into pandas DataFrame for efficient data access
        try:
            self.projected_data = pd.read_csv(projected_file)
        except pd.errors.EmptyDataError as e:
            raise ValueError(
                f"Projected points file has no data or is corrupted: {projected_file}. "
                f"Original error: {e}. Run player data fetcher to regenerate this file."
            )

        # Create a normalized lowercase name column for case-insensitive player matching
        # This improves matching reliability and performance by avoiding repeated string operations
        # Example: "Patrick Mahomes" -> "patrick mahomes"
        self.projected_data['name_lower'] = (
            self.projected_data['name'].str.lower().str.strip()
        )

    def get_projected_points(self, player, week_num):
        """
        Get projected points for a specific player and week.

        Args:
            player: FantasyPlayer object
            week_num: Week number (1-17)

        Returns:
            float: Projected points for the week, or None if not available
        """
        # Safety check: If data failed to load, return None
        if self.projected_data is None:
            return None

        # Normalize player name for case-insensitive matching
        # Must match the normalization applied during data load
        player_name_lower = player.name.lower().strip()

        # Construct column name for the requested week
        # CSV format: 'week_1_points', 'week_2_points', etc.
        week_col = f'week_{week_num}_points'

        # Query DataFrame for matching player row using normalized name
        # Returns a DataFrame with 0 or 1 rows
        match = self.projected_data[
            self.projected_data['name_lower'] == player_name_lower
        ]

        # Validate match found and week column exists
        # match.empty = True if player not found in dataset
        # week_col not in match.columns = True if week data doesn't exist
        if match.empty or week_col not in match.columns:
            return None

        # Extract projected points value from the first (and only) matching row
        # Use iloc[0] to get the first row, then access the week column
        projected_value = match.iloc[0][week_col]

        # Handle missing data (NaN values in CSV)
        # NaN occurs when a projection wasn't available for that player/week
        if pd.isna(projected_value):
            return None

        # Convert to float and return
        # Pandas may return numpy types, so explicit float conversion ensures consistency
        return float(projected_value)

    def get_projected_points_array(self, player, start_week, end_week):
        """
        Get array of projected points for a range of weeks.

        Args:
            player: FantasyPlayer object
            start_week: Starting week number (inclusive)
            end_week: Ending week number (inclusive)

        Returns:
            list: List of projected points (floats) for each week.
                  None values indicate unavailable data.
        """
        # Build list of projected points for consecutive weeks
        projected_array = []

        # Iterate through each week in the range (inclusive of both endpoints)
        # range(start_week, end_week + 1) includes end_week
        # Example: range(1, 3+1) = [1, 2, 3]
        for week_num in range(start_week, end_week + 1):
            # Get projected points for this week (may return None if unavailable)
            projected = self.get_projected_points(player, week_num)
            projected_array.append(projected)

        # Return list with one entry per week
        # Example: [18.5, 20.3, None, 19.1] for 4 weeks with week 3 missing data
        return projected_array

    def get_historical_projected_points(self, player):
        """
        Get all historical projected points up to current week - 1.

        This is a convenience method for performance calculations that need
        projected points for weeks 1 through (CURRENT_NFL_WEEK - 1).

        Args:
            player: FantasyPlayer object

        Returns:
            list: List of projected points for weeks 1 to (CURRENT_NFL_WEEK - 1)
        """
        # Get current NFL week from config
        # This tells us which week we're currently in
        current_week = self.config.current_nfl_week

        # Edge case: If we're in week 1, there is no historical data yet
        # Return empty list since no weeks have been completed
        if current_week <= 1:
            return []

        # Get projected points for all completed weeks (1 through current-1)
        # Example: If current_week=5, return projections for weeks [1, 2, 3, 4]
        # These are "historical" because they're in the past relative to current week
        return self.get_projected_points_array(player, 1, current_week - 1)
