BASE_CONFIG_PARAMS = [
    'CURRENT_NFL_WEEK',
    'NFL_SEASON',
    'NFL_SCORING_FORMAT',
    'DRAFT_NORMALIZATION_MAX_SCALE',
    'SAME_POS_BYE_WEIGHT',
    'DIFF_POS_BYE_WEIGHT',
    'INJURY_PENALTIES',
    'DRAFT_ORDER_BONUSES',
    'DRAFT_ORDER_FILE',
    'DRAFT_ORDER',
    'MAX_POSITIONS',
    'FLEX_ELIGIBLE_POSITIONS',
    'ADP_SCORING',
    'PLAYER_RATING_SCORING'
]

WEEK_SPECIFIC_PARAMS = [
    'NORMALIZATION_MAX_SCALE',
    'TEAM_QUALITY_SCORING',
    'PERFORMANCE_SCORING',
    'MATCHUP_SCORING',
    'SCHEDULE_SCORING',
    'TEMPERATURE_SCORING',
    'WIND_SCORING',
    'LOCATION_MODIFIERS'
]
