#!/usr/bin/env python3
"""
Generate team_data folder from players_actual.csv for simulation system.

This script creates per-team CSV files in sim_data/team_data/ containing:
- Fantasy points allowed by position (QB, RB, WR, TE, K)
- Total points scored and allowed for offensive/defensive rankings

Usage:
    python generate_team_data.py

The script reads from sim_data/:
- players_actual.csv: Player weekly fantasy points
- season_schedule.csv: Team opponents by week

And generates sim_data/team_data/:
- KC.csv, MIN.csv, etc. (32 team files)

Author: Generated by Claude Code
"""

import csv
import sys
from pathlib import Path
from collections import defaultdict

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))
from utils.LoggingManager import setup_logger, get_logger


def load_players_actual(filepath: Path) -> list:
    """Load players_actual.csv and return list of player dicts."""
    players = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            players.append(row)
    return players


def load_season_schedule(filepath: Path) -> dict:
    """
    Load season_schedule.csv and return dict mapping (week, team) -> opponent.

    Returns:
        Dict[(week, team)] -> opponent
    """
    schedule = {}
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            week = int(row['week'])
            team = row['team']
            opponent = row['opponent']
            schedule[(week, team)] = opponent
    return schedule


def generate_team_data(data_folder: Path) -> None:
    """
    Generate team_data folder from players_actual.csv.

    For each team and week, calculates:
    - QB, RB, WR, TE, K: Fantasy points allowed to that position
    - points_scored: Sum of team's offensive fantasy points
    - points_allowed: Sum of opponent's offensive fantasy points

    Args:
        data_folder: Path to sim_data folder containing source files
    """
    logger = get_logger()

    # Load source data
    players_file = data_folder / "players_actual.csv"
    schedule_file = data_folder / "season_schedule.csv"

    if not players_file.exists():
        raise FileNotFoundError(f"players_actual.csv not found: {players_file}")
    if not schedule_file.exists():
        raise FileNotFoundError(f"season_schedule.csv not found: {schedule_file}")

    players = load_players_actual(players_file)
    schedule = load_season_schedule(schedule_file)

    logger.info(f"Loaded {len(players)} players and {len(schedule)} schedule entries")

    # All 32 NFL teams
    all_teams = [
        'ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE',
        'DAL', 'DEN', 'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC',
        'LAC', 'LAR', 'LV', 'MIA', 'MIN', 'NE', 'NO', 'NYG',
        'NYJ', 'PHI', 'PIT', 'SEA', 'SF', 'TB', 'TEN', 'WSH'
    ]

    # Initialize data structure: {team: {week: {QB: 0, RB: 0, ...}}}
    team_data = {team: {} for team in all_teams}
    for team in all_teams:
        for week in range(1, 18):  # Weeks 1-17
            team_data[team][week] = {
                'QB': 0.0, 'RB': 0.0, 'WR': 0.0, 'TE': 0.0, 'K': 0.0,
                'points_scored': 0.0, 'points_allowed': 0.0
            }

    # Process each player's weekly points
    positions = ['QB', 'RB', 'WR', 'TE', 'K']

    for player in players:
        position = player.get('position', '')
        player_team = player.get('team', '')

        if position not in positions or player_team not in all_teams:
            continue

        for week in range(1, 18):
            week_col = f'week_{week}_points'
            try:
                week_points = float(player.get(week_col, 0) or 0)
            except (ValueError, TypeError):
                week_points = 0.0

            if week_points <= 0:
                continue

            # Add to team's points_scored
            team_data[player_team][week]['points_scored'] += week_points

            # Find opponent and add to their position-specific points allowed
            opponent = schedule.get((week, player_team))
            if opponent and opponent in all_teams:
                team_data[opponent][week][position] += week_points
                team_data[opponent][week]['points_allowed'] += week_points

    # Create output folder
    output_folder = data_folder / "team_data"
    output_folder.mkdir(exist_ok=True)

    # Write team files
    for team in all_teams:
        team_file = output_folder / f"{team}.csv"

        with open(team_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['week', 'pts_allowed_to_QB', 'pts_allowed_to_RB', 'pts_allowed_to_WR',
                           'pts_allowed_to_TE', 'pts_allowed_to_K', 'points_scored', 'points_allowed'])

            for week in range(1, 18):
                week_data = team_data[team][week]
                writer.writerow([
                    week,
                    round(week_data['QB'], 1),
                    round(week_data['RB'], 1),
                    round(week_data['WR'], 1),
                    round(week_data['TE'], 1),
                    round(week_data['K'], 1),
                    round(week_data['points_scored'], 1),
                    round(week_data['points_allowed'], 1)
                ])

        logger.debug(f"Generated {team}.csv")

    logger.info(f"Generated team_data folder with {len(all_teams)} team files in {output_folder}")


def main():
    """Main entry point for generate_team_data script."""
    # Setup logging
    setup_logger(name="generate_team_data", level="INFO")
    logger = get_logger()

    # Determine data folder
    script_dir = Path(__file__).parent
    data_folder = script_dir / "sim_data"

    if not data_folder.exists():
        logger.error(f"Data folder not found: {data_folder}")
        sys.exit(1)

    logger.info(f"Generating team_data from {data_folder}")

    try:
        generate_team_data(data_folder)
        logger.info("Team data generation complete")
    except Exception as e:
        logger.error(f"Failed to generate team data: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
